# This is a basic workflow to help you get started with Actions

name: Generate Data

# Controls when the workflow will run
on:
  # scheduled every night at 00:00
  schedule:
    # https://crontab.guru/#45_23_*_*_*
    # every night at 11:00
    - cron: "45 23 * * *"

  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Python dependencies
        run: pip install --upgrade pip && pip install wheel && pip install -r requirements.txt
        
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "kaizer1v"
          git config user.email "kaizer1v@gmail.com"

      - name: ✅ Generate Data
        run: |
          echo "Scraping start!"
          python main.py
          echo "Scraping end!"
      
      - name: Commit changes
        run: |
          set -e
          git commit -am "data updated on - $(date)"
          git push --force-with-lease origin main
