# This is a basic workflow to help you get started with Actions

name: Generate Data

# Controls when the workflow will run
on:
  schedule:
    # every night at 00:00
    - cron: "0 0 0 1/1 * ? *"
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Python dependencies
        run: pip install --upgrade pip && pip install wheel && pip install -r requirements.txt

      - name: Generate Data
        run: |
          echo "Generating cases & cowin vaccination data"
          mkdir ./_data
          python main.py
          echo "Job Completed!"
